name: Test

on:
  push:

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
          cache: "pip"
          cache-dependency-path: src/main/backend/requirements.txt

      - run: pip install -r src/main/backend/requirements.txt

      - run: pytest

  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
          cache-dependency-path: package-lock.json

      - run: npm ci

      - run: npm run test --workspace=src/main/frontend
